### ISSUE TITLE
Installer empty

### ISSUE THREAD

**Issue by easiexd** [OlaYZen/OlaiOS#2]
Every fucking installer is empty for fuck sake. Fix it now! I demand it!

**Comment by OlaYZen** [comment]
I'm sorry for this misunderstanding, in the wiki its says that it's still a project which is still not working yet, but im working on  a quick fix that will make at least one of the Desktop Environment. Join my Discord for the news and updates for OlaiOS

**Comment by easiexd** [comment]
it states no such thing in the wiki

**Comment by OlaYZen** [comment]
# Installer
It states on FaQ that im working on it, and it can take some time

## Discord
- [Discord](https://discord.com/invite/poki)

### More Questions
If theres any more question just comment under my comment and ill try answering as fast as i can

**Comment by easiexd** [comment]
danke danke shön
